### ISSUE TITLE
Program List: Static UI

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#44]
The scope of this ticket is to create a static layout of the Program List page. To do this:

- [x] 1 - Integrate the page title bar
- [x] 2 - Integrate the sub-navigation component
- [x] 3 -  Integrate the container component
- [x] 4 -  Integrate the table component action bar + footer (just a bottom border)
- [x] 5 -  Integrate the table body component
- [x] 6 -  Integrate button component with "Create a Program" button
- [ ] 7 -  Integrate action tooltips (see below)

**Zeplin:** https://zpl.io/blDwDnP
![all-programs](https://user-images.githubusercontent.com/18424138/59046034-308f4380-884f-11e9-81ad-ac61b87ef9d0.png)

**Action tooltips:**
Hover over user icons: tooltip reads, "Manage users" 
Hover over pencil icon: tooltip reads, "Edit profile" 

eg. 
![Screen Shot 2019-05-29 at 4 50 10 PM](https://user-images.githubusercontent.com/18424138/58590322-db8d7500-8231-11e9-8085-2f699b8ed1b1.png)

**Comment by kcullion** [comment]
Looking good @hlminh2000! I know this ticket is still in progress but we had some feedback about the components that are there and thought I'd write it down here for now:

1. Please change the appbar from min-height:68px to height:56px (hey look, divisible by 8!). The min-height is making it grow really large on my big screen.
2. For the left sidebar, please tighten up the secondary item. So change to font-size:14px and make it so the height is 34px instead of 40px (I couldn't find where the top and bottom padding were being set using inspector)
3. when you implement the 8px grid, we can revisit this - but we think the left sidebar can be thinner so there's more room for the content section.

**Comment by kcullion** [comment]
@hlminh2000 a couple more things I noticed:
1. Left sidebar - the active state for the secondary item - the font should be the secondary blue.
![Screen Shot 2019-06-13 at 9 27 41 AM](https://user-images.githubusercontent.com/18424138/59436557-dbf34780-8dbd-11e9-8a59-23c47332a7fd.png)

2. When I click on an item I get this very harsh outline on the item - is that an accessibility/browser thing?
![Screen Shot 2019-06-13 at 9 39 53 AM](https://user-images.githubusercontent.com/18424138/59437303-52447980-8dbf-11e9-97f6-2cb805005015.png)

3. I don't see the hand cursor on the table header item - Rosi did see it. Is that something we can force with css cursor:pointer ?

**Comment by hlminh2000** [comment]
@kcullion thanks kim! :) I addressed point 1). For point 2, I've updated it  so that it'd go away once you finish clicking it, but yes it's the browser's native behaviour for buttons, which allows the DOM element to be accessed by the keyboard.

**Comment by rosibaj** [comment]
@hlminh2000 just a question - why do we see they keyboard navigation highlight when clicking not with the keyboard though? for example here: https://developer.mozilla.org/en-US/docs/Web/Accessibility/Keyboard-navigable_JavaScript_widgets when i use keyboard navigation i see the blue highlight.  When i navigate the menu with mouse though, i never see the highlight even when clicking.
