### ISSUE TITLE
Program Page: Users Tab Static UI 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#54]
The scope of this ticket is to create a static layout of the User List page in the Program Admin Area. To do this:

- [x] 1 -  Integrate the container component
- [x] 2 -  Integrate the tab component
- [ ] 3 -  Integrate the table component header & footer
-- header should have bulk actions with invite and delete 
-- footer does NOT need pagenation - should just be a bottom border for the table (pagenation is shown here just for component library)
- [x] 4 -  Integrate the table body component
- [x] 5 -  Integrate button component with "Add Users" button
- [x] 6 - Integrate action tooltips (see below)
NOTE - DO NOT INCLUDE SEARCH ON THIS TABLE

Zeplin: https://zpl.io/aBRPxwA
![all-users](https://user-images.githubusercontent.com/18424138/59047707-58cc7180-8852-11e9-8fab-f703549e6b7f.png)

**Action tooltips:**
Hover over mail icon: tooltip reads, "Resend invitation" 
Hover over pencil icon: tooltip reads, "Edit user" 
Hover over garbage icon: tooltip reads, "Remove user" 

eg. 
![Screen Shot 2019-05-29 at 5 02 41 PM](https://user-images.githubusercontent.com/18424138/58591132-9bc78d00-8233-11e9-8ec5-1942b4149535.png)

**Comment by ciaranschutte** [comment]
@kcullion just noting our slack convo here.
no bulk actions for now

**Comment by ciaranschutte** [comment]
@ciaranschutte Animation on checkbox not working yet

**Comment by ciaranschutte** [comment]
@kcullion @rosibaj ready to preview. animation on checkbox isn't working on table. i will circle back on this.

**Comment by kcullion** [comment]
@ciaranschutte thanks! Here's some feedback:

- [ ] we actually can remove the checkbox column since we aren't going to do bulk actions here at this point
- [ ] I think we should make the email address a "mailto:" link so it's easy for program admin to click on and email users (@rosibaj, @alekspejovic  what do you think?)
- [ ] @rosibaj @alekspejovic what date format should we decide on? We should make this consistent throughout the system. MM/DD/YYYY or DD/MM/YYYY or Month Day, Year (like Jan. 1, 2019)
- [ ] the icons look a bit small, can you make sure they are 20px x 20px. I actually missed this on this page too: https://platform-ui.qa.argo.cancercollaboratory.org/programs. Can you fix those icons while you are at it? (should the "action row" be a component for reuse?)

**Comment by rosibaj** [comment]
@kcullion Agree with mail-to as well; that would be very nice!

**Comment by kcullion** [comment]
@ciaranschutte to followup on the above

- [ ] please include the mailto for the email addresses (I just made a link component ticket if you need to wait to use that)
- [ ] We are going to go with the International  date format: YYYY-MM-DD

**Comment by ciaranschutte** [comment]
@rosibaj @kcullion https://platform-ui.qa.argo.cancercollaboratory.org/program-management

**Comment by rosibaj** [comment]
@ciaranschutte Looks great!!!!
