### ISSUE TITLE
UI Component Library: Table Body

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#59]
**Table Header:**
- [x] Sortable (with double arrow icon)
- [x] Not sortable 
- [x] Sorted (with arrow icon - top or bottom are blue depending on the sort order)
- [ ] Select all - checkbox (when clicked, all rows of the table are selected)

![Screen Shot 2019-05-24 at 11 00 31 AM](https://user-images.githubusercontent.com/18424138/58337182-3169b380-7e13-11e9-9b18-7383dd6c6252.png)

**Cells:**
- [x] Default
- [x] Row hover (full row turns grey on cell hover)
- [x] Zebra stripe (alternate row shading)
- [x] Selected (full row is selected when the row checkbox is checked)
- [ ] Percentage (blue shaded background fills based on the percentage of the cell width)
- [x] Checkbox (this column is fixed on the left - so if the table is horizontally scrollable, this column stays fixed and always available)
- [ ] Actions (this column is fixed on the right - so if the table is horizontally scrollable, this column stays fixed and always  available)

![Screen Shot 2019-05-24 at 10 23 45 AM](https://user-images.githubusercontent.com/18424138/58334665-0b8de000-7e0e-11e9-83ed-a0168e7cc675.png)

Zeplin:https://zpl.io/adzPEOR
See in page: https://zpl.io/aBRPxwA

**Related tickets:**
Table Action bar: https://github.com/icgc-argo/argo-platform/issues/42
Table footer: https://github.com/icgc-argo/argo-platform/issues/60

See this article for a prototype of fixed header and horizontal scroll with fixed column:
https://uxdesign.cc/design-better-data-tables-4ecc99d23356

**Comment by hlminh2000** [comment]
some Notes:
- [ ] Select all - checkbox (when clicked, all rows of the table are selected)
The table is set up to support this, however setting up the story to show the full interaction is more work than we want to do, and it'll have to be reimplemented in the application regardless. So the story is only showing the static state for this.

The following points will be implemented as part of the development of the page rather than the UI component:
- [ ] Actions (this column is fixed on the right - so if the table is horizontally scrollable, this column stays fixed and always  available)
- [ ] Percentage (blue shaded background fills based on the percentage of the cell width)

(The last one can be done as a reusable UI component, however it's not a part of the table inherently)

**Comment by kcullion** [comment]
Thanks @hlminh2000, this sounds good

Can we make the cell padding (sm lg) an option to select? So this version would be large then we can do a smaller one for data heavy tables.

**Comment by hlminh2000** [comment]
definitely @kcullion! But yeah it doesn't have to be done now, we can certainly delay this till when we have the need and design for it :)

**Comment by kcullion** [comment]
@hlminh2000 this looks good to me. 
I just moved the percentage cell to it's own component: https://github.com/icgc-argo/argo-platform/issues/74

The action specifics will be moved to be page specific

**Comment by hlminh2000** [comment]
thanks @kcullion! Closing this ticket now
