### ISSUE TITLE
UI Component Library: Page title bar

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-platform#62]
- [x] Text and / icon: shows the user where they are within the submission system
- [ ] Actions - general section actions can show up as buttons or links on the right hand side (optional)

EG.
![Screen Shot 2019-06-06 at 1 48 44 PM](https://user-images.githubusercontent.com/18424138/59054499-d5b31780-8861-11e9-9ce6-265e0659903c.png)

Zeplin: https://zpl.io/adzPEOR
See in page: https://zpl.io/blDwDnP
https://zpl.io/aBRPxwA

**Comment by kcullion** [comment]
@d8660091 sorry my mistake - I didn't mean for this title bar to contain links - like breadcrumbs. So I changed the design so it didn't use royal blue and the slash icon is now a chevron. 

Can you make those changes as seen in Zeplin: https://zpl.io/adzPEOR

![Screen Shot 2019-06-04 at 5 03 00 PM](https://user-images.githubusercontent.com/18424138/58913641-a3cb7500-86ea-11e9-96e7-6a7761de13f9.png)

**Comment by hlminh2000** [comment]
@d8660091 @kcullion so this seems to be one of those grey areas where it's not clear what is reusable and what isn't. So what do you guys think about the following approach:
1) Ignoring the fact that we already have quite some work put into the logic to render a "breadscrumb"-like visual, every page seems to have different content in the bar, so `TitleBar` should be just an empty white container with padding, border, and text style. (This is worth generalizing as it's pretty much there in every page)
2) Since we do already have great work going into the breadscrumbs-like structure, it can be made a separate component, which is used in the program's specific page. (might as well call it Breadscrumb?)

This makes the `TitleBar` component un-opinionated about its contents, but still keeps the style consistent. Best way to get the point of a component across is probably to add a couple stories for the component with different sample usages
