### ISSUE TITLE
Gateway: Update/Remove User 

### ISSUE THREAD

**Issue by rosibaj** [icgc-argo/argo-platform#99]
The gateway needs to be able to send a user invitation to support the UI to invite a user

**UI Flow for this Need:**
Update User
![image](https://user-images.githubusercontent.com/15824252/59697622-31639600-91bc-11e9-97b0-03400099e8f5.png)

Remove User
![image](https://user-images.githubusercontent.com/15824252/59697751-68d24280-91bc-11e9-9360-7a0ca20e0c15.png)

**Inputs to  GraphQL**
Update User
- first name
- last name
- role 
- ego user id
- program id [MAYBE SHORT NAME - need to confirm with @Buwujiu ]

**Processing Service**
Program Service (Update User and Remove User)

**Output - What happens on a successful event?**
When an user is edited, their role/name reflects correctly on ui
When an user is removed, their role/name reflects correctly on ui

**Comment by joneubank** [comment]
@alekspejovic On Update User - are we allowing program managers to change the name of their users? This seems strange to me, something usually managed by each individual user, no?

On the technical side, ProgramService lets us change the Role for the user for a specific program. would be a separate request to change names since this isnt tied to a specific program.

**Comment by rosibaj** [comment]
@joneubank  No name change allowed please! Small mistake on our part there - only ROLE should be updateable
